---
title: "05_Anova"
format: html

---
```{r - load data : foret}
load("Data/foret.Rdata")
 
```




```{r - ANOVA for species and genus }

#ANOVA for species  
aov2 <- aov(leaf.thick~For.type+Species, data = foret)
summary(aov2)
#ANOVA for genus
aov3 <- aov(leaf.thick~For.type+genus, data = foret)
summary(aov3)



AIC(aov2,aov3)
BIC(aov2,aov3)
```



```{r}
#For loop for ANOVA

responses <- c("For.type", "Species", "Ind.number", "leaf.thick", "leaf.area", "spec.leaf.area", "leaf.dry.mat.cont", "leaf.tissue.dens", "twig.dry.mat.cont", "twig.tis.dens", "bark.thick", "bark.dry.mat.cont", "bark.tis.dens", "stem.dry.mat.cont", "stem.tis.dens", "leaf.C.cont", "leaf.N.cont", "leaf.P.cont", "leaf.C.N.ratio", "leaf.C.P.ratio", "leaf.N.P.ratio", "twig.C.cont", "twig.N.cont", "twig.P.cont", "twig.C.N.ratio", "twig.C.P.ratio", "twig.N.P.ratio", "bark.C.cont", "bark.N.cont", "bark.P.cont", "bark.C.N.ratio", "bark.C.P.ratio", "bark.N.P.ratio", "stem.C.content","stem.N.cont", "stem.P.cont", "stem.C.N.ratio", "stem.C.P.ratio", "stem.N.P.ratio")



aov2 <- aov(leaf.thick ~ For.type + Species, data = foret )
summary(aov2)


results <- data.frame(
  Trait = responses,
  P_value_ForType = NA,
  P_value_Species = NA
)
```


```{r}
# Corrected lines in the For loop for ANOVA

for (var in responses) {

    # Check first if variable exists in the dataset
    if (!(var %in% names(foret))) { # Using foret_clean is better here
        cat("\nSkipping", var, "-- variable not found in dataset.\n")
        next
    }

    # Model 1: Species + Forest Type
    formula1 <- as.formula(paste(var, "~ Species + For.type"))
    # *** FIX HERE: Change 'foret' to 'foret_clean' ***
    model1 <- try(aov(formula1, data = foret), silent = TRUE) 

    # Model 2: Genus + Forest Type
    formula2 <- as.formula(paste(var, "~ genus + For.type"))
    # *** FIX HERE: Change 'foret' to 'foret_clean' ***
    model2 <- try(aov(formula2, data = foret), silent = TRUE) 

    cat("\n==========================================\n")
    cat("ANOVA Results for:", var, "\n")
    cat("==========================================\n")

    # Print Model 1
    cat("\n📌 Model 1: Species + For.type\n")
    if (inherits(model1, "try-error")) {
        cat("ERROR for Model 1:", var, "\n")
    } else {
        print(summary(model1))
    }

    # Print Model 2
    cat("\n📌 Model 2: genus + For.type\n")
    if (inherits(model2, "try-error")) {
        cat("ERROR for Model 2:", var, "\n")
    } else {
        print(summary(model2))
    }
}


```

```{r}
#Table for ANOVA and BIC

# Create a data frame to store results
Table.aov1.aov2 <- data.frame(
  Trait = c("leaf.thick", "leaf.area", "spec.leaf.area", "leaf.dry.mat.cont", "leaf.tissue.dens", "twig.dry.mat.cont", "twig.tis.dens", "bark.thick", "bark.dry.mat.cont", "bark.tis.dens", "stem.dry.mat.cont", "stem.tis.dens", "leaf.C.cont", "leaf.N.cont", "leaf.P.cont", "leaf.C.N.ratio", "leaf.C.P.ratio", "leaf.N.P.ratio", "twig.C.cont", "twig.N.cont", "twig.P.cont", "twig.C.N.ratio", "twig.C.P.ratio", "twig.N.P.ratio", "bark.C.cont", "bark.N.cont", "bark.P.cont", "bark.C.N.ratio", "bark.C.P.ratio", "bark.N.P.ratio", "stem.C.content","stem.N.cont", "stem.P.cont", "stem.C.N.ratio", "stem.C.P.ratio", "stem.N.P.ratio"),
  P_value_species = NA,
  P_value_genus = NA
)

# List all trait columns (numeric variables)
trait_cols <- names(foret)[sapply(foret, is.numeric)]

# Create empty dataframe
p_table <- data.frame(
  Trait = trait_cols,
  P_value_species = NA,
  P_value_genus = NA
)

# Loop through traits
for (i in seq_along(trait_cols[-1]) +1) {
  trait <- trait_cols[i]
  
  # ANOVA for species
  model_species <- aov(foret[[trait]] ~ Species, data = foret)
  p_species <- summary(model_species)[[1]][["Pr(>F)"]][1]
  
  # ANOVA for genus
  model_genus <- aov(foret[[trait]] ~ genus, data = foret)
  p_genus <- summary(model_genus)[[1]][["Pr(>F)"]][1]
  
  # Save into table
  p_table$P_value_species[i] <- p_species
  p_table$P_value_genus[i] <- p_genus
}

# Print table
p_table

p_table$P_value_genus>0.05
p_table$P_value_species>0.05
```

All variables have significant differences between forest types (see @tbl-anova)
```{r tbl-anova}
#| tbl-cap: P value for ANOVA

library(knitr)
p_table$P_value_species <- as.character(p_table$P_value_species)
p_table$P_value_genus <- as.character(p_table$P_value_genus)

p_table <- p_table[-1, ]
row.names(p_table) <- NULL

kable(p_table)


```

