---
title: "06 - PRINCIPAL COMPONNET ANALYSIS"
format: html
---

```{r}
library(stringr)
#Load the data
load("Data/foret.Rdata")
foret$genus <- word(foret$Species, 1)


```

```{r}
ls()
str(foret)
#foret_active <- foret[, c(2:4, 6:10)]
foret_active <- foret[, sapply(foret, is.numeric)]
head(foret)
summary(foret)

```

```{r}
# The pacakages should  be installed for running the PCA design plot
#install.packages(c("FactoMineR", ""))
```

```{r}
scale. = TRUE 
pca_base <- prcomp(foret_active, center = TRUE, scale. = TRUE)
summary(pca_base)
print(pca_base$rotation)
biplot(pca_base)
biplot(pca_base, cex = c(0.8, 1.2))

```

```{r}
# The libararies  are to be loaded for running the PCA design plot
#library(FactoMineR)
#library(factoextra)

graph = FALSE 
res.pca <- PCA(foret_active, scale.unit = TRUE, graph = FALSE)
fviz_eig(res.pca, addlabels = TRUE)
fviz_pca_var(res.pca, col.var = "black")
fviz_pca_var(res.pca)

fviz_pca_ind(res.pca,
             geom.ind = "point", # show points only (not text labels)
             col.ind = "cos2",   # Color by quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE)

fviz_pca_biplot(res.pca,)
```


```{r}

df <- data.frame(
  other_var = c("a", "b", "c"),
  bark.thick = as.character(c(1.5, 2.1, 1.8)),
  bark.dry.mat.cont = as.character(c(0.4, 0.5, 0.3)),
  stem.tis.dens = as.character(c(0.6, 0.7, 0.5)),
  stringsAsFactors = FALSE
)

# A vector containing the names of the columns you want to convert
my_variables <- c("bark.thick", "bark.dry.mat.cont", "bark.tis.dens", "stem.dry.mat.cont", "stem.tis.dens", "bark.C.cont", "bark.N.cont", "bark.P.cont","bark.C.N.ratio", "bark.C.P.ratio", "bark.N.P.ratio", "stem.C.content","stem.N.cont", "stem.P.cont", "stem.C.P.ratio", "stem.N.P.ratio", "stem.C.N.ratio")

for(i in my_variables){
  foret[[i ]] <- as.numeric(foret[[i]])
}

numerical_vars <- names(foret)[sapply(foret, is.numeric)]
numerical_vars <- names(foret)[!sapply(foret, is.numeric)]
foret$bark.thick <- as.numeric(foret$bark.thick)

```


```{r}

res.pca <- prcomp(foret[, 3:10],  scale = TRUE)


group_variable <- foret$For.type
fviz_pca_biplot(res.pca, 
                # Color individuals by the 'Species' variable
                habillage = group_variable,
                addEllipses = TRUE, # Optional: Add ellipses around groups
                ellipse.level = 0.95, # Optional: Set ellipse confidence level
                label = "var", # Only label variables (arrows/text)
                repel = TRUE, # Avoid text overlapping
                ggtheme = theme_minimal() # Use a clean ggplot theme
                )

            
                
```


```{r}

res.pca <- prcomp(foret[, 3:10],  scale = TRUE)


group_variable <- foret$genus
fviz_pca_biplot(res.pca, 
                # Color individuals by the 'Species' variable
                habillage = group_variable,
                addEllipses = TRUE, # Optional: Add ellipses around groups
                ellipse.level = 0.95, # Optional: Set ellipse confidence level
                label = "var", # Only label variables (arrows/text)
                repel = TRUE, # Avoid text overlapping
                ggtheme = theme_minimal() # Use a clean ggplot theme
                )

```


```{r}

  # Line to remove the legend of the genus
    res.pca <- prcomp(foret[, 3:10], scale. = TRUE) # Corrected scale argument to scale.

group_variable <- foret$genus

fviz_pca_biplot(res.pca,
                # Color individuals by the 'genus' variable
                habillage = group_variable,
                addEllipses = TRUE,
                ellipse.level = 0.95,
                label = "var",
                repel = TRUE,
                ggtheme = theme_minimal()
) +

  ggplot2::theme(legend.position = "none")        
                

```

